### ISSUE TITLE
使用枚举作为查询条件时，结果总为0条

### ISSUE THREAD

**Issue by aboutZZ** [xuejmnet/easy-query#152]
实体类中使用了枚举，对应地，数据库中存储的是**枚举名**(不是数字)。使用该字段作为查询条件时，查询出结果总是为0条。

```java
// 枚举
public enum MaintenanceState {
    // 未保养
    PENDING,
    // 已完成
    FINISHED
}


// 实体类：
public class MaintenanceLog {
    @Column(primaryKey = true, generatedKey = true)
    private Long id;
    // 维修状态
    private MaintenanceState state;
    // 其他字段省略
}


// 查询：
easyQuery.queryable(MaintenanceLogDO.class)
  .where((log) -> {
     log.eq(MaintenanceLog::getState, queryVO.getState());
}).toList();
```

查询日志：
```
Preparing: SELECT id,state FROM emp_maintenance_log WHERE state = ?
Parameters: PENDING(MaintenanceState)
Time Elapsed: 38(ms)
Total: 0
```

**Comment by xuejmnet** [comment]
@aboutZZ 您好感谢您使用本框架 https://xuejm.gitee.io/easy-query-doc/guide/config/value-converter.html 看看这个文档

**Comment by aboutZZ** [comment]
使用ValueConverter报错： `MaintenanceLogDO.state conversion unknown`

```java
// 实体类：
public class MaintenanceLog {
    @Column(primaryKey = true, generatedKey = true)
    private Long id;
    // 维修状态
    @Column(conversion = EnumConverter.class)
    private MaintenanceState state;
}

public class EasyQueryEnumConverter implements ValueConverter<Enum<?>, String> {
    @Override
    public String serialize(Enum<?> anEnum, ColumnMetadata columnMetadata) {
        // return ValueConverter.super.serialize(anEnum, columnMetadata);
        return anEnum.name();
    }

    @Override
    public Enum<?> deserialize(String s, ColumnMetadata columnMetadata) {
        return ValueConverter.super.deserialize(s, columnMetadata);
    }
}
```

查询时报错：（在获取`ValueConverter`时，从 `valueConverterMap` 中以 `MaintenanceState.class` 为键获取，因此获取不到`Enum`类的`ValueConverter`）
```
com.easy.query.core.exception.EasyQueryException: MaintenanceLogDO.state conversion unknown
	at com.easy.query.core.metadata.EntityMetadata.init(EntityMetadata.java:246)
	at com.easy.query.core.metadata.DefaultEntityMetadataManager.getEntityMetadata(DefaultEntityMetadataManager.java:39)
	at com.easy.query.core.api.def.DefaultSQLClientApiFactory.createQueryable(DefaultSQLClientApiFactory.java:89)
	at com.easy.query.core.api.client.DefaultEasyQueryClient.queryable(DefaultEasyQueryClient.java:62)
	at com.easy.query.api4j.client.DefaultEasyQuery.queryable(DefaultEasyQuery.java:48)
```

还是说必须要像文档中那样所有枚举必须搞个`IEnum`接口？

**Comment by xuejmnet** [comment]
@Override
    public Enum<?> deserialize(String s, ColumnMetadata columnMetadata) {
        return ValueConverter.super.deserialize(s, columnMetadata);
    }


这段代码不对按照文档来或者自己实现，super是接口没有任何实现

**Comment by xuejmnet** [comment]
你可以通过自定义注解@EnumValue或者自定义接口来实现反序列化的枚举属性获取

**Comment by xuejmnet** [comment]
源码里面有单元测试也有对应的代码

**Comment by xuejmnet** [comment]
deserialize 这个方法第一个String值是数据库的值你可以通过自定义接口或者自定义注解来实现，我这边demo文档给出的是自定义接口，因为switch是高效的，自定义枚举是干净的编码方式但是高效程度而言还是switch高效，当然整体不会差很多只是相对而言

**Comment by aboutZZ** [comment]
好的，感谢您的解答。
